services:
  appbundle.menu.voter.request:
    class: AppBundle\Menu\RequestVoter
    arguments:
      - @service_container
    tags:
      - { name: knp_menu.voter }

  neo4j_client:
    class: AppBundle\Neo4j\ConnectionBuilder
    arguments:
      - "%neo4j_protocol%"
      - "%neo4j_host%"
      - "%neo4j_port%"
      - "%neo4j_user%"
      - "%neo4j_password%"
